# Generated by Django 4.0.1 on 2022-02-17 15:57

from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('pet_type', models.TextField(blank=True, null=True)),
                ('external_id', models.TextField()),
                ('name', models.TextField()),
                ('sex', models.TextField(choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')])),
                ('age', models.TextField()),
                ('vet_peculiarities', models.TextField()),
                ('flea_treatment', models.TextField()),
                ('fur_type', models.TextField()),
                ('character', models.TextField()),
                ('feeding', models.TextField()),
                ('litter_box_trained', models.TextField()),
                ('in_catalog_since', models.TextField()),
                ('shelter', models.TextField()),
                ('curator_info', models.TextField()),
                ('height', models.TextField()),
                ('breed', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pets.models.upload_gallery_image)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
