# Generated by Django 4.0.1 on 2022-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_created',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
